Lambda-School-Labs/school-calendar-fe

school-cal/README.md, school-cal/package-lock.json, school-cal/package.json, school-cal/src/App.css
=> Started Project

school-cal/src/components/logincomp.js, school-cal/src/index.css
connected to firebase and added tooltips to say when you mess up yourlogin
=> added tooltips for invalid stuff

school-cal/src/firebase/index.js
=> added firebase functions to react app

school-cal/src/components/AdminRegister/index.js, school-cal/src/components/Login/index.js, school-cal/src/components/StudentRegister/index.js
=> Added routes to components

school-cal/src/AppRouter.js, school-cal/src/components/StudentLogin/index.js, school-cal/src/components/StudentRegister/index.js
=> Added StudentLogin boilerplate

school-cal/.gitignore, school-cal/src/components/AdminRegister/index.js, school-cal/src/components/Navbar/index.js, school-cal/src/contexts/auth/authState.js, school-cal/src/routes/privateRoute.js
AdminRegister is now using AuthContext functions to register a new admin.
=> wired AdminRegister to AuthContext

school-cal/.gitignore
=> Removed package-lock from gitignore

school-cal/src/components/AdminDashboard/AdminDashboard.js
=> wired admindashboard to firebase

school-cal/package.json, school-cal/src/App.css, school-cal/src/components/AdminLogin/index.js, school-cal/src/firebase/index.js
Added snackbars to pop up when invalid email or password
=> Added Snackbars to login page, pops up on invalid email or password

school-cal/package.json, school-cal/src/AppRouter.js, school-cal/src/components/AdminDashboard/AdminAddEvent.js, school-cal/src/components/AdminDashboard/AdminDashboard.js
=> Carlos hernandez

school-cal/public/index.html, school-cal/src/components/AdminRegister/AdminRegisterForm.js, school-cal/src/components/AdminRegister/index.js, school-cal/src/contexts/auth/authReducer.js, school-cal/src/contexts/auth/authState.js, school-cal/src/firebase/index.js, school-cal/src/utilities/googleAPI/index.js
added sign-in with Google to Admin Register
=> refactored Admin Register to use Formik and Yup

school-cal/src/AppRouter.js, school-cal/src/components/AdminLogin/index.js, school-cal/src/firebase/index.js, school-cal/src/pages/Registration/RegistrationForm.js, school-cal/src/pages/Registration/index.js
- moved Registration to the pages dir
- added userRole select to Registration page
- added password confirmation to Registration page
=> renamed AdminRegister to Registration

school-cal/src/AppRouter.js, school-cal/src/pages/Registration/RegistrationForm.js, school-cal/src/pages/SignIn/SignInForm.js, school-cal/src/pages/SignIn/index.js
=> Signin page

school-cal/src/components/Navbar/index.js, school-cal/src/contexts/auth/authState.js
=> updated google-signin

school-cal/src/pages/AdminDashboard/index.js
=> updated side drawer aesthetic

netlify.toml
=> added toml file

school-cal/src/components/Events/EventDisplay.css, school-cal/src/components/Events/EventDisplay.js
=> Dynamic calendar

school-cal/src/components/AdminDashboard/index.js, school-cal/src/config/firebase/index.js, school-cal/src/pages/AdminDashboard/AdminDashboard.js, school-cal/src/pages/AdminDashboard/index.js
=> Addcalendar

school-cal/package-lock.json, school-cal/package.json, school-cal/src/AppRouter.js, school-cal/src/components/Routes/PrivateRoute.js, school-cal/src/contexts/auth/authReducer.js, school-cal/src/contexts/auth/authState.js, school-cal/src/pages/Registration/RegistrationForm.js, school-cal/src/pages/Registration/index.js, school-cal/src/pages/SignIn/SignInForm.js, school-cal/src/pages/SignIn/index.js, school-cal/src/utilities/api/index.js, school-cal/src/utilities/localStorage/index.js
=> Development node

school-cal/package-lock.json, school-cal/package.json, school-cal/src/components/AdminDashboard/index.js, school-cal/src/index.js, school-cal/src/pages/AdminDashboard/index.js, school-cal/src/pages/Landing/index.js, school-cal/src/pages/Registration/index.js, school-cal/src/pages/SignIn/index.js
=> fixed analytics bugs

school-cal/src/AppRouter.js, school-cal/src/components/AdminDashboard/index.js, school-cal/src/components/Events/EventDisplay.js, school-cal/src/components/addUserTwilioMessage/index.js, school-cal/src/components/sidebar/index.js, school-cal/src/pages/AdminDashboard/index.js, school-cal/src/pages/StudentDashboard/index.js
=> twilio added to frontend(unstyled)

school-cal/src/components/Calendar/index.js, school-cal/src/components/Events/CreateEvent.js, school-cal/src/contexts/calendar/calendarState.js, school-cal/src/pages/AdminDashboard/index.js
=> added clickable date to create a new event

school-cal/src/components/Calendar/index.js, school-cal/src/components/Navbar/signinnav.js, school-cal/src/components/sidebar/index.js, school-cal/src/contexts/auth/authReducer.js, school-cal/src/contexts/auth/authState.js, school-cal/src/contexts/calendar/calendarState.js, school-cal/src/pages/Registration/RegistrationForm.js, school-cal/src/pages/Registration/index.js, school-cal/src/pages/SignIn/SignInForm.js, school-cal/src/pages/SignIn/index.js, school-cal/src/utilities/api/index.js, school-cal/src/utilities/localStorage/index.js
=> fixed axios token issue, fixed login and registration styling

school-cal/src/utilities/api/index.js
=> fixed api base url

school-cal/src/index.css, school-cal/src/pages/marketing/index.js
=> added media queries

school-cal/src/components/SideMenu/index.js, school-cal/src/pages/AdminDashboard/index.js
=> changed Sidebar to SideMenu

school-cal/package-lock.json, school-cal/src/components/Calendar/index.js, school-cal/src/components/Events/addSubscriber.js
=> added add subscriber btn with twilio

school-cal/src/components/SideMenu/index.js, school-cal/src/pages/AdminDashboard/index.js
=> moving useEffect order to calendar

school-cal/src/components/SideMenu/index.js, school-cal/src/contexts/calendar/calendarState.js
=> fixed calendar select dropdown initial value

school-cal/src/components/Calendar/index.js, school-cal/src/components/Events/CreateEvent.js, school-cal/src/components/Events/EditEvent.js, school-cal/src/contexts/calendar/calendarState.js
- User is able to schedule a full-day event by clicking a check box.
- User is able to edit a full-day event to a partial day event.
=> All day event

school-cal/src/components/Calendar/index.js
=> updated event properties

school-cal/src/contexts/calendar/calendarState.js, school-cal/src/pages/CalendarSettings/index.js
=> attempted to fix calendar settings, seems to work

school-cal/src/pages/marketing/index.js
=> Added styles to the icons

school-cal/src/components/Calendar/index.js, school-cal/src/contexts/calendar/calendarReducer.js
=> updated calendar reducer event format

school-cal/src/components/Calendar/index.js
=> update moment format for fullcalendar

school-cal/src/components/Calendar/index.js
=> fixing all day event by adding a day

school-cal/src/components/Calendar/index.js, school-cal/src/contexts/calendar/calendarReducer.js
=> fixing all-day event

school-cal/src/components/Calendar/index.js, school-cal/src/components/Events/CreateEvent.js
=> removed logging

school-cal/src/components/CalendarSettings/Privacy.js, school-cal/src/components/SideMenu/MoreUpcomingEvents.js, school-cal/src/components/SideMenu/MyCalendars.js, school-cal/src/components/SideMenu/UpcomingEvents.js, school-cal/src/components/SideMenu/index.js, school-cal/src/pages/AdminDashboard/index.js, school-cal/src/pages/CalendarSettings/index.js
=> Upcoming events

school-cal/src/components/SideMenu/MoreUpcomingEvents.js, school-cal/src/components/SideMenu/UpcomingEvents.js
=> fixed listitemavatar warning

school-cal/src/components/SideMenu/MyCalendars.js, school-cal/src/components/SideMenu/index.js, school-cal/src/contexts/calendar/calendarReducer.js, school-cal/src/contexts/calendar/calendarState.js, school-cal/src/pages/CalendarSettings/index.js
=> fix calendar settings

school-cal/src/components/CalendarSettings/Privacy.js, school-cal/src/pages/Subscribe/index.js
=> updated subscribableLink route

school-cal/.prettierrc, school-cal/src/components/Calendar/index.js, school-cal/src/contexts/calendar/calendarReducer.js, school-cal/src/contexts/calendar/calendarState.js
=> added_displaying_recurring_events

school-cal/src/components/Calendar/index.js, school-cal/src/contexts/calendar/calendarReducer.js
=> updated fullcalendar endate exclusive

school-cal/src/components/Calendar/index.js, school-cal/src/contexts/calendar/calendarState.js
=> updated recurring events display

school-cal/src/contexts/calendar/calendarReducer.js
=> updated date format

school-cal/src/pages/marketing/index.js
=> Landing page iii

school-cal/src/components/Events/CreateEvent.js
=> updated create event

school-cal/src/components/Calendar/index.js, school-cal/src/components/CalendarSettings/Delete.js, school-cal/src/components/Events/CreateEvent.js, school-cal/src/components/Events/EditEvent.js, school-cal/src/components/SideMenu/MyCalendars.js, school-cal/src/components/SideMenu/UpcomingEvents.js, school-cal/src/components/SideMenu/index.js, school-cal/src/pages/CalendarSettings/index.js, school-cal/src/pages/marketing/index.js
=> updated drag & drop

README.md
=> added more detail

README.md
=> added numbering

school-cal/src/components/Calendar/index.js, school-cal/src/components/Events/CreateEvent.js, school-cal/src/components/Events/RepeatEvent.js, school-cal/src/contexts/calendar/calendarState.js
=> added recurring event

school-cal/src/components/Calendar/index.js, school-cal/src/components/SideMenu/index.js
=> updated side bar styling

school-cal/src/components/SideMenu/SubscribedCalendars.js, school-cal/src/contexts/calendar/calendarReducer.js
=> fixed subscribe calendar duplicate

school-cal/package-lock.json, school-cal/src/components/Calendar/index.js, school-cal/src/components/Events/CustomNotification.js
Twilio routes will not work until heroku is updated to reflect recent back end changes
=> Updated subscriber button and added Send Notification Button

src/contexts/AuthContext.js, src/hooks/useAuth.js, src/index.js
=> Auth context

.vscode/settings.json, src/components/Home/Sidebar.js, src/components/Home/blank.js
Co-authored-by: Jeremy McWilliams <j2macwilliams@gmail.com>
=> profile display

.vscode/settings.json, src/components/Home/Home.js, src/components/Home/Navbarhome.js, src/components/Home/Sidebar.js, src/components/Home/createEventModal.js
=> Create event modal

package-lock.json, package.json, src/App.test.js, src/components/Splash/RegisterModal.js, src/contexts/AuthContext.js, src/test/Context.spec.js, src/test/Register.spec.js
=> test-user-auth

src/components/Home/Home.js, src/components/Home/Navbar.js
=> Comment out unneeded code.

src/components/Splash/LoginBar.js, src/test/Login.spec.js
=> Create failing test for required Login password.

README.md, src/test/Login.spec.js
=> add code climate badge to readme.

src/components/Home/Sidebar.js
=> Fix spacing in sidebar.

package.json, src/App.js, src/components/Home/Calendar/Cells.js, src/components/Home/Events.js, src/components/Home/ProfileDisplay.js, src/components/Home/Sidebar.js, src/components/Home/index.js, src/components/Redirect.js, src/components/Splash/LoginBar.js
=> Work redirect to home with events. Work questionable profile display.

.github/workflows/ci.yml, package.json
=> Add Code Climate coverage yml file. Change package.json.

src/components/Home/Calendar/Calendar.js
=> Work bugs for .env secrets.

netlify.toml
=> Add toml file to root directory.

public/_redirects
=> work redirects.

public/_redirects
=> Change redirect file.

netlify.toml, public/_redirects
=> Refactor calendar

src/components/Home/index.js
=> Add .env secret to axios call.

src/components/Home/index.js
=> Hardcode in events endpoint.

package.json
=> Code Coverage

package.json, src/App.css, src/components/Authenticate.js, src/components/Home/index.js, src/utils/axiosWithAuth.js
=> change to get events showing on calendar

src/components/Home/Calendar/Calendar.js, src/components/Home/Template.js, src/components/Home/index.js, src/contexts/Context.js, src/hooks/useTemplate.js, src/index.js
Co-authored by: j2macwilliams
Co-authored by: Kennethaustin
=> add initial addTemplate, move selected into index

src/components/Home/Calendar/Calendar.js, src/components/Home/index.js
=> Date on click

src/components/PrivateRoute.js, src/gapi/calendarApi.js, src/hooks/useGapi.js
=> Auth with gapi

src/components/Events.js, src/components/Home/Calendar/Calendar.js, src/components/Home/index.js
=> wip gapi changes

src/components/Home/Calendar/Day.js, src/components/Home/index.js, src/gapi/calendarApi.js
Co-authored by:dstadz
Co-authored by:drejohnson
Co-authored by:juarezfrench
=> Execute the event into primary Calendar! Wooo Hooo.

src/App.js, src/components/Loading.js, src/components/Template.js, src/hooks/useDate.js, src/hooks/useGapi.js, src/hooks/useTemplate.js, src/routes/Dashboard.js, src/routes/Welcome.js
=> Styling and restructure

src/components/EventsIndicator.js
Events do not excessively repeat on current day
=> altered hasEvents to account for events without datetime

package.json, src/components/Calendar.js, yarn.lock
Arrows around the month name no longer expand and contract with the length of the month name
=> Static month arrows

src/routes/Dashboard.js
Changed hard-coded timezone offset when adding a new event to be dynamic.
- [✔] Bug fix (non-breaking change which fixes an issue)
- [✔] Complete, but not tested (may need new tests)
=> added dynamic timezones

src/routes/Dashboard.js
Set the title field to be required so that it doesn't crash the app when an event is submitted without a title
=> Title field is required

src/components/Template.js
=> toggled templates now act as intended.

src/components/dashboardComponents/ChooseDateForm.js, src/components/dashboardComponents/Dashboard.js, src/components/dashboardComponents/calendarComponents/Calendar.js, src/components/dashboardComponents/calendarComponents/Day.js
Highlight calendar when ready to accept date selection
Gives better user feedback
Design
=> Choose date highlight

src/components/dashboardComponents/Dashboard.js
=> Resolving military time

src/components/dashboardComponents/ChooseDateForm.js, src/components/dashboardComponents/CreateTemplateForm.js, src/components/dashboardComponents/Dashboard.js
Altered military time conversion such that events would still submit correctly
Timezone conversion was getting thrown off by military time conversion. Changed the code such that retrieving data from or adding to the server does not change, just the display to the user changes, thus not interfering with event creation
=> times converting correctly and dates submitting

src/App.js, src/components/dashboardComponents/TemplateContainer.js, src/components/mobile/NewEventForm.js
new event form according to mobile-first design. styling needs to be further flushed in additional iteration. 
=> skeleton of new event form

package.json, setup-jest.js, src/App.spec.js, src/__snapshots__/App.spec.js.snap, src/components/Welcome.js, src/components/dashboardComponents/CreateTemplateForm.js, src/components/dashboardComponents/CreateTemplateForm.spec.js, src/components/dashboardComponents/Dashboard.js, src/components/dashboardComponents/ProfileInfo.spec.js, src/components/dashboardComponents/TemplateContainer.js, src/components/dashboardComponents/TemplateContainer.spec.js, src/components/dashboardComponents/__mocks__/Dashboard.js, src/components/dashboardComponents/calendarComponents/Calendar.js, src/components/dashboardComponents/calendarComponents/Day.js, src/components/dashboardComponents/calendarComponents/Days.js, src/components/dashboardComponents/calendarComponents/EventsIndicator.spec.js, src/setupTests.js, test/utils/test-utils.js, yarn.lock
=> Testing using mocks

src/App.js, src/components/dashboardComponents/ChooseDateForm.js, src/components/dashboardComponents/CreateTemplateForm.js, src/components/dashboardComponents/Dashboard.js, src/components/dashboardComponents/ProfileInfo.js, src/components/dashboardComponents/TemplateContainer.js, src/components/dashboardComponents/calendarComponents/Calendar.js, src/components/dashboardComponents/calendarComponents/Day.js, src/components/dashboardComponents/calendarComponents/Days.js, src/components/mobile/Calendar.js, src/components/mobile/Dashboard.js, src/components/mobile/Mobile.js, src/components/mobile/NavigationComponents/BotNav.js
calendar fixed at 24 months for development
=> Fixed 24 months

package.json, src/App.js, src/components/mobile/Calendar.js, src/components/mobile/ConfirmDatesBtn.js, src/components/mobile/Dashboard.js, src/components/mobile/InfiniteCalendar.js, src/components/mobile/Mobile.js, src/components/mobile/NewInfCal.js, src/components/mobile/eventComponents/MobileChooseDateForm.js, src/components/mobile/eventComponents/MobileEvents.js, src/components/mobile/eventComponents/MobileTemplateContainer.js, yarn.lock
Calendar loads 50 months smoothly
=> Trash calendar

src/components/Header.js, src/components/dashboardComponents/CreateTemplateForm.js, src/components/dashboardComponents/calendarComponents/Day.js, src/components/mobile/ConfirmDatesBtn.js, src/components/mobile/Dashboard.js, src/components/mobile/InfiniteCalendar.js, src/components/mobile/Mobile.js, src/components/mobile/MobileCalendar.js, src/components/mobile/NavigationComponents/Nav.js, src/components/mobile/NewInfCal.js, src/components/mobile/eventComponents/MobileChooseDateForm.js, src/components/mobile/eventComponents/MobileEvents.js, src/components/mobile/eventComponents/NewEventForm.js
=> general clean up and renaming

src/components/dashboardComponents/calendarComponents/Day.js, src/components/mobile/ConfirmDatesBtn.js, src/components/mobile/Dashboard.js, src/components/mobile/Mobile.js, src/components/mobile/MobileCalendar.js, src/components/mobile/NavigationComponents/Nav.js, src/components/mobile/NewInfCal.js
confirm dates button responsive, does not hide nav, calendar has responsiveness, no highlight in mobile view.
=> confirm date btn truncates event name and calendar responsive

src/components/mobile/Dashboard.js, src/components/mobile/MobileCalendar.js, src/components/mobile/MobileDay.js, src/components/mobile/MobileDays.js, src/components/mobile/MobileEventIndicator.js, src/components/mobile/NavigationComponents/Nav.js, src/components/mobile/NewInfCal.js
Changed event mapping from inside the day component up to dashboard
Slow updating when clicking a day to to add to a template.
=> Change event mapping

src/components/Header.js, src/components/mobile/InfiniteCal.js, src/components/mobile/Mobile.js, src/components/mobile/MobileCalendar.js
Changed calendar to fit without horizontal scroll, removed calendar props, default view is now calendar instead of groups
=> changed styling, removed unnecessary props, default view is calendar

src/components/mobile/Mobile.js, src/components/mobile/eventComponents/NewEventForm.js, src/utils/helperFunctions.js
New event forms works as intended
it was getting a 500 error on submission
=> Make new event form functional

src/components/mobile/Groups.js, src/components/mobile/Hamburger/TopNav.js, src/components/mobile/MobileDashboard.js, src/components/mobile/eventComponents/MobileTemplateContainer.js, src/components/mobile/eventComponents/NewEventForm.js
styling changes to add event form and addition of profile image in hamburger menu
=> Add form stying

src/components/dashboardComponents/ProfileInfo.js, src/components/mobile/Hamburger/TopNav.js
=> Add profile img

src/components/mobile/Hamburger/TopNav.js
=> fixed photo broken link

src/components/mobile/Hamburger/TopNav.js, src/components/mobile/Mobile.js, src/components/mobile/MobileDashboard.js, src/components/mobile/eventComponents/MobileEvents.js, src/components/mobile/eventComponents/MobileTemplateContainer.js, src/components/mobile/eventComponents/NewEventForm.js
=> Changed on click to on submit

src/components/mobile/Hamburger/TopNav.js
=> added image

src/components/mobile/Mobile.js, src/components/mobile/eventComponents/MobileChooseDateForm.js, src/components/mobile/eventComponents/MobileTemplateContainer.js
=> added delete functionality on long press

package.json
=> took out homepage

src/components/mobile/AddEventButton.js, src/components/mobile/ConfirmDatesBtn.js, src/components/mobile/Hamburger/TopNav.js
=> fixed styles for mobile

src/App.js, src/components/Authenticate.js, src/components/mobile/AddEventButton.js, src/components/mobile/CalendarLoading.js, src/components/mobile/ConfirmDatesBtn.js, src/components/mobile/Hamburger/TopNav.js, src/components/mobile/InfiniteCal.js, src/components/mobile/InfiniteCalendar.js, src/components/mobile/Mobile.js, src/components/mobile/MobileCalendar.js, src/components/mobile/MobileDashboard.js, src/components/mobile/MobileDay.js, src/components/mobile/MobileEventIndicator.js, src/components/mobile/NavigationComponents/Nav.js, src/components/mobile/NavigationComponents/TopNav.js, src/components/mobile/eventComponents/MobileChooseDateForm.js, src/components/mobile/eventComponents/MobileEvents.js, src/components/mobile/eventComponents/MobileTemplateContainer.js, src/components/mobile/eventComponents/NewEventForm.js, src/contexts/auth.js, src/hooks/useDate.js, src/hooks/useGapi.js, src/utils/calendarApi.js, src/utils/helperFunctions.js
=> added comments to describe code

src/components/home/Dashboard.js, src/components/navigation/Hamburger/TopNav.css, src/components/navigation/Hamburger/TopNav.js, src/components/navigation/Nav.js
=> footer to refactor 2

src/components/home/Dashboard.js, src/components/home/Home.js, src/utils/calendarApi.js
=> Refactor desktop

src/components/events/ConfirmDatesBtn.js, src/components/events/NewEventForm.js, src/index.js
=> added toast notification after creating new event

package.json, src/components/navigation/Hamburger/TopNav.css, src/components/navigation/Hamburger/TopNav.js
=> footer - fixed styling for icon and signout button

src/components/mobile/AddEventButton.js, src/components/mobile/InfiniteCal.js, src/components/mobile/Mobile.js, src/components/mobile/NavigationComponents/Nav.js, src/utils/theme.js
=> adjusted add event button styling and the mobile nav icons styling

package.json, src/components/events/ChooseDateForm.js, src/components/events/TemplateContainer.js, src/components/events/UpdateEventForm.js, src/components/home/Dashboard.js, src/components/home/Home.js, src/utils/axiosWithAuth.js, src/utils/helperFunctions.js
Add ability to delete and update templates
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Complete, but not tested (may need new tests)
- [x ] I have performed a self-review of my own code
- [x ] My changes generate no new warnings
=> CRUD for templates

package.json, src/components/calendar/Calendar.js, src/components/calendar/Day.js, src/components/calendar/Days.js, src/components/home/Dashboard.js, src/hooks/useDate.js
=> Date styling logic

src/components/home/Dashboard.js, src/components/home/Home.js, src/components/navigation/Nav.js
=> made mobile desktop transition dynamic

src/components/navigation/Nav.js
Co-authored-by: Katya katya.p.1129@gmail.com
=> made desktop sidebar functional

src/components/calendar/Days.js, src/components/groups/CreateNewGroup.js, src/components/groups/Groups.js, src/components/home/Home.js, src/utils/axiosWithAuth.js
=> Create new group

src/components/groups/AdminContactForm.js, src/components/groups/CreateNewGroup.js, src/components/groups/Groups.js, src/components/home/Home.js
=> Add contact to group

src/App.js, src/components/groups/AddContactForm.js, src/utils/axiosWithAuth.js
add ability to add contacts 
- [ x] New feature (non-breaking change which adds functionality)
- [x ] Complete, but not tested (may need new tests)
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] My code has been reviewed by at least one peer
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
=> Contacts form

src/components/home/Home.js
Fixes desktop display bug
- [x ] Bug fix (non-breaking change which fixes an issue)
=> fix desktop display bug

src/components/contacts/Contacts.js, src/components/groups/Groups.js, src/components/home/Home.js
=> View contacts

src/components/calendar/Days.js
=> error fixed

src/components/contacts/Contacts.js, src/components/groups/CreateNewGroup.js, src/components/groups/Groups.js
=> Contact functionality

src/components/contacts/Contacts.js, src/components/groups/InviteLink.js, src/components/groups/InviteeAddContactForm.js, src/components/home/Home.js
=> Invite contact

src/components/events/EventIndicator.js, src/components/groups/CreateNewGroup.js, src/components/home/Home.js
=> fixed loading bug

src/components/events/EventIndicator.js, src/components/events/EventPage.js
=> solved the loading bug

src/components/events/EventsContainer.js, src/components/events/NewEventForm.js, src/components/events/TemplateContainer.js, src/components/home/Home.js, src/components/navigation/Nav.js, src/index.js
=> updated events

src/components/events/EventPage.js, src/components/events/Events.js, src/components/events/EventsContainer.js, src/components/events/NewEventForm.js, src/components/events/TemplateContainer.js, src/components/navigation/Nav.js
=> Events styling

src/components/contacts/AddContactToGroupForm.js, src/components/groups/CreateNewGroup.js, src/components/groups/Groups.js
=> added animation to group.js arrows

src/components/groups/EditGroupForm.js, src/components/groups/Groups.js, src/components/groups/GroupsContainer.js, src/components/home/Home.js
=> fix edit group display bug
